const fs = require('fs')
const crypto = require('crypto')
const ID_PATTERN = /^[a-z][a-z0-9-]{5,63}$/
const CAMPUS = { '学院路': 'xueyuan_road', '学院路校区': 'xueyuan_road', '沙河': 'shahe', '沙河校区': 'shahe' }
const SPORT_CATEGORY = { '健身房': 'gym', '球类': 'ball_sports', '游泳': 'swimming', '田径场': 'track_and_other', '操场': 'track_and_other' }
const MEALS = { '早餐': 'breakfast', '午餐': 'lunch', '晚餐': 'dinner', '夜宵': 'late_night' }
const NULL_TEXT = new Set(['', '无', '暂无', '不适用', '未知', '待确认'])
function parseCsvBuffer(buffer) {
  if (!(buffer[0] === 0xef && buffer[1] === 0xbb && buffer[2] === 0xbf)) throw new Error('CSV 必须为 UTF-8 with BOM')
  const text = buffer.toString('utf8').replace(/^\uFEFF/, ''); const rows = []; let row = []; let field = ''; let quoted = false
  for (let i = 0; i < text.length; i += 1) { const char = text[i]; if (quoted) { if (char === '"' && text[i + 1] === '"') { field += '"'; i += 1 } else if (char === '"') quoted = false; else field += char } else if (char === '"') quoted = true; else if (char === ',') { row.push(field); field = '' } else if (char === '\n') { row.push(field.replace(/\r$/, '')); rows.push(row); row = []; field = '' } else field += char }
  if (quoted) throw new Error('CSV 存在未闭合引号'); if (field || row.length) { row.push(field.replace(/\r$/, '')); rows.push(row) }
  const headers = rows.shift().map((value) => value.trim()); if (!headers.length || new Set(headers).size !== headers.length) throw new Error('CSV 表头为空或重复')
  return rows.filter((values) => values.some((value) => value.trim())).map((values, index) => { if (values.length !== headers.length) throw new Error(`第 ${index + 2} 行列数 ${values.length}，应为 ${headers.length}`); return Object.fromEntries(headers.map((header, column) => [header, values[column].trim()])) })
}
function readCsv(filePath) { return parseCsvBuffer(fs.readFileSync(filePath)) }
function nullable(value) { const normalized = String(value || '').trim(); return NULL_TEXT.has(normalized) ? null : normalized }
function uniqueList(value) { return [...new Set(String(value || '').split(/[;；、/]/).map((item) => item.trim()).filter((item) => !NULL_TEXT.has(item)))] }
function bool(value) { return value === '是' ? true : value === '否' ? false : null }
function date(value) { if (!value) return null; const match = value.match(/^(\d{4})[-/](\d{1,2})[-/](\d{1,2})$/); if (!match) throw new Error(`日期格式错误：${value}`); const result = `${match[1]}-${match[2].padStart(2, '0')}-${match[3].padStart(2, '0')}`; if (Number.isNaN(Date.parse(`${result}T00:00:00Z`))) throw new Error(`日期无效：${value}`); return result }
function hash(value, length = 10) { return crypto.createHash('sha256').update(value).digest('hex').slice(0, length) }
function stableId(prefix, campus, kind, identity) { const id = `${prefix}-${campus === 'xueyuan_road' ? 'xueyuan' : campus}-${kind}-${hash(identity)}`; if (!ID_PATTERN.test(id)) throw new Error(`生成 ID 不合法：${id}`); return id }
function contentHash(record) { const copy = { ...record }; delete copy.contentHash; delete copy.createdAt; delete copy.updatedAt; delete copy.dataVersion; return crypto.createHash('sha256').update(JSON.stringify(copy)).digest('hex') }
function metadata(row, dataVersion) { return { dataVersion, status: 'pending_verification', verifiedAt: null, validUntil: null, sourceType: row['信息来源'] === '学生整理' ? 'student_curated' : 'other', sourceText: row['信息来源'] || '学生整理', curatedBy: '学生整理', displayNotice: '人工整理、信息仅供参考', imageFileId: null } }
function campusOf(value) { if (!CAMPUS[value]) throw new Error(`未知校区：${value}`); return CAMPUS[value] }
function capabilities(activities, category) { const text = activities.join('|'); const tags = []; if (/跑步|田径/.test(text)) tags.push('running_track'); if (/散步|走/.test(text)) tags.push('walkable_route'); if (/力量/.test(text) || category === 'gym') tags.push('strength_equipment'); if (/拉伸|休闲/.test(text)) tags.push('open_space'); if (/团体/.test(text)) tags.push('group_fitness_space'); return [...new Set(tags)] }
function finish(record, idField) { record._id = record[idField]; record.contentHash = contentHash(record); return record }
function mapVenue(row, dataVersion) { const campus = campusOf(row['校区']); const category = SPORT_CATEGORY[row['场地类别']]; if (!category) throw new Error(`未知场地类别：${row['场地类别']}`); const supportedActivities = uniqueList(row['支持的运动']); const identity = [campus, row['场地名称'], row['具体位置']].join('|'); return finish({ venueId: stableId('venue', campus, category.replaceAll('_', '-'), identity), campus, originalName: row['场地名称'], name: row['场地名称'], insideOrOutsideCampus: row['校内或校外'] === '校内' ? 'inside' : row['校内或校外'] === '校外' ? 'outside' : 'unknown', category, subcategory: row['场地类别'], locationText: row['具体位置'], supportedActivities, capabilityTags: capabilities(supportedActivities, category), equipmentTags: uniqueList(row['现有器材']), indoorOutdoor: row['室内或室外'] === '室内' ? 'indoor' : row['室内或室外'] === '室外' ? 'outdoor' : 'unknown', openHoursText: nullable(row['开放时间']), reservationRequired: bool(row['是否预约']), reservationMethod: nullable(row['预约方式']), priceText: nullable(row['收费说明']), priceCny: null, confirmedAt: date(row['确认日期']), description: nullable(row['备注']), ...metadata(row, dataVersion) }, 'venueId') }
function externalMerchant(row) { return nullable(row['楼层']) === null && (/外卖|商家/.test(row['具体位置']) || /外卖|商家/.test(row['备注'])) }
function merchantSlug(name) { return name === '蔓味轻食' ? 'manwei-light-meal' : `merchant-${hash(name, 8)}` }
function openHoursFromNote(note) { const match = String(note || '').match(/供应时间[：:]\s*(\d{1,2}:\d{2})-(\d{1,2}:\d{2})/); return match ? `${match[1].padStart(5, '0')}-${match[2].padStart(5, '0')}` : null }
function mapHall(row, dataVersion) { const campus = campusOf(row['校区']); const floor = nullable(row['楼层']); const isExternal = externalMerchant(row); if (!isExternal && !floor) throw new Error('校内食堂必须填写楼层'); const campusSlug = campus === 'xueyuan_road' ? 'xueyuan-road' : campus; const identity = isExternal ? [campus, row['食堂名称']].join('|') : [campus, row['食堂名称'], floor, row['具体位置']].join('|'); const diningHallId = isExternal ? `dining-${campusSlug}-${merchantSlug(row['食堂名称'])}` : stableId('dining', campus, 'hall', identity); if (!ID_PATTERN.test(diningHallId)) throw new Error(`生成 ID 不合法：${diningHallId}`); return finish({ diningHallId, entityType: isExternal ? 'external_merchant' : 'campus_dining_hall', campus, insideOrOutsideCampus: isExternal ? 'outside' : 'inside', originalName: row['食堂名称'], name: row['食堂名称'], floor, locationText: row['具体位置'], openHoursText: isExternal ? openHoursFromNote(row['备注']) : null, mealPeriodText: { breakfast: nullable(row['早餐时间']), lunch: nullable(row['午餐时间']), dinner: nullable(row['晚餐时间']), lateNight: nullable(row['夜宵时间']) }, halalAvailable: bool(row['是否有清真餐饮']), confirmedAt: date(row['确认日期']), description: nullable(row['备注']), ...metadata(row, dataVersion) }, 'diningHallId') }
function foodGroups(row) { return { staples: uniqueList(row['主食']), vegetables: uniqueList(row['蔬菜']), proteins: uniqueList(row['蛋白质来源']) } }
function mapFood(row, hall, dataVersion) { const campus = campusOf(row['校区']); const floor = nullable(row['楼层']); const identity = hall.entityType === 'external_merchant' ? [campus, row['食堂名称'], row['菜品名称']].join('|') : [campus, row['食堂名称'], floor, row['菜品名称']].join('|'); const priceText = nullable(row['价格说明']); const groups = foodGroups(row); return finish({ foodOptionId: stableId('food', campus, 'option', identity), campus, insideOrOutsideCampus: row['校内/校外'] === '校内' ? 'inside' : row['校内/校外'] === '校外' ? 'outside' : 'unknown', serviceMode: row['堂食/外卖'] === '堂食' ? 'dine_in' : row['堂食/外卖'] === '外卖' ? 'delivery' : 'unknown', diningHallId: hall.diningHallId, diningHallName: row['食堂名称'], floorOrStall: floor, originalName: row['菜品名称'], dishName: row['菜品名称'], category: /减脂|健康/.test(row['菜品名称']) ? 'healthy_light_meal' : 'other_food', mealPeriods: uniqueList(row['供应餐次']).map((item) => MEALS[item]).filter(Boolean), foodGroupTags: groups, foodTags: [...new Set([...groups.staples, ...groups.vegetables, ...groups.proteins])], cookingMethodText: nullable(row['烹饪方式']), priceText, priceCny: priceText && /^\d+(\.\d{1,2})?$/.test(priceText) ? Number(priceText) : null, servingText: null, nutrition: { estimatedKcal: null, otherText: null }, nutritionSource: { kcalSourceText: null, originalKcalText: nullable(row['热量k']) }, supplyDaysText: nullable(row['供应时间或星期']), confirmedAt: date(row['确认日期']), description: nullable(row['备注']), ...metadata(row, dataVersion) }, 'foodOptionId') }
function buildResources({ venueRows, hallRows, foodRows, dataVersion }) { const errors = []; const blocked = []; const safeMap = (rows, mapper, type) => rows.flatMap((row, index) => { try { return [mapper(row)] } catch (error) { errors.push({ type, row: index + 2, name: row['场地名称'] || row['食堂名称'] || row['菜品名称'], reason: error.message }); return [] } }); const venues = safeMap(venueRows, (row) => mapVenue(row, dataVersion), 'venue'); const diningHalls = safeMap(hallRows, (row) => mapHall(row, dataVersion), 'diningHall'); const foodOptions = []; foodRows.forEach((row, index) => { const campus = CAMPUS[row['校区']]; const floor = nullable(row['楼层']); const hall = diningHalls.find((item) => item.campus === campus && item.name === row['食堂名称'] && (item.entityType === 'external_merchant' || item.floor === floor)); if (!hall) { blocked.push({ type: 'foodOption', row: index + 2, name: row['菜品名称'], parent: `${row['食堂名称']} ${row['楼层']}`, reason: '找不到对应餐厅父记录' }); return } try { foodOptions.push(mapFood(row, hall, dataVersion)) } catch (error) { errors.push({ type: 'foodOption', row: index + 2, name: row['菜品名称'], reason: error.message }) } }); const all = [...venues, ...diningHalls, ...foodOptions]; if (new Set(all.map((item) => item._id)).size !== all.length) errors.push({ type: 'batch', reason: '生成了重复稳定 ID' }); return { schemaVersion: '1.0.0', resourceDataVersion: dataVersion, collections: { campus_venues: venues, campus_dining_halls: diningHalls, campus_food_options: foodOptions }, blocked, errors } }
function compare(records, existing = []) { const byId = new Map(existing.map((item) => [item._id, item])); const result = { insert: [], update: [], unchanged: [] }; records.forEach((item) => { const before = byId.get(item._id); if (!before) result.insert.push(item._id); else if (before.contentHash === item.contentHash) result.unchanged.push(item._id); else result.update.push(item._id) }); return result }
module.exports = { ID_PATTERN, parseCsvBuffer, readCsv, uniqueList, date, stableId, contentHash, buildResources, compare }
